# Generated by Django 5.2.4 on 2025-08-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientinfo',
        ),
    ]
