# Generated by Django 5.2.4 on 2025-08-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='FTA_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='FTA_password',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='Trade_licence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='VAT_TRN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
