# Generated by Django 5.2.4 on 2025-08-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientinfo_fta_email_clientinfo_fta_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientinfo',
            old_name='Trade_licence',
            new_name='Trade_licenceNum',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='Financial_year',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='Tax_return_months',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='representative_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='representative_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
