# Generated by Django 5.2.4 on 2025-08-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_rename_trade_licence_clientinfo_trade_licencenum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='onboarding_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
