# Generated by Django 5.2.4 on 2025-08-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_clientinfo_address_clientinfo_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='industry',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='clients.service'),
        ),
    ]
