# Generated by Django 5.2.4 on 2025-08-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_service_clientinfo_industry_clientinfo_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientinfo',
            old_name='onboarding_data',
            new_name='onboarding_date',
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='FTA_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='Financial_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='Tax_return_months',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='Trade_licenceNum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='VAT_TRN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='representative_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='representative_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='clients', to='clients.service'),
        ),
    ]
