# Generated by Django 5.2.4 on 2025-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_rename_onboarding_data_clientinfo_onboarding_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
