# Generated by Django 5.2.4 on 2025-08-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientinfo_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='notes',
        ),
    ]
