# Generated by Django 5.2.4 on 2025-08-11 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_remove_clientinfo_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='Trade_licenceNum',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='industry',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='staff_assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
