# Generated by Django 5.2.4 on 2025-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_remove_clientinfo_trade_licencenum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='finyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='Financial_year',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='Financial_year',
            field=models.ManyToManyField(blank=True, max_length=100, null=True, related_name='Financial_year', to='clients.finyear'),
        ),
    ]
