# Generated by Django 5.2.4 on 2025-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_finyear_remove_clientinfo_financial_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='next_CT_return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='next_VAT_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
