# Generated by Django 5.2.4 on 2025-08-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_clientinfo_next_ct_return_clientinfo_next_vat_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='Financial_year',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='Financial_year', to='clients.finyear'),
        ),
    ]
