# Generated by Django 5.2.4 on 2025-08-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_alter_clientinfo_financial_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='Financial_year',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='financial_year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='financial_year_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
