# Generated by Django 5.2.4 on 2025-08-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_remove_clientinfo_financial_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
