# Generated by Django 5.2.4 on 2025-08-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_clientinfo_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='financial_year_end',
        ),
        migrations.RemoveField(
            model_name='clientinfo',
            name='financial_year_start',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='financial_year',
            field=models.CharField(blank=True, null=True),
        ),
    ]
