# Generated by Django 5.2.4 on 2025-08-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_remove_clientinfo_financial_year_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientinfo',
            old_name='Tax_return_months',
            new_name='vat_return_months',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='ct_financial_year',
            field=models.CharField(blank=True, null=True),
        ),
    ]
